#+title: Cinco libros para entender el Holocausto del Palacio de Justicia 
#+author: Juan E. Gómez-Morantes
#+date: 2023:12:29

Hay muchas fechas que "han partido en dos" la historia de Colombia, pero pocas han sido capaz de retratar la historia reciente de Colombia de una forma tan cruda y espectacular como el 6 de noviembre de 1985, cuando el M-19 se tomó el Palacio de Justicia, y el estado colombiano lo retomó a, literalmente, sangre y fuego.

Este artículo presenta cinco libros centrados en diferentes aspectos de este evento y un breve comentario sobre cada uno de ellos. 

* Carrigan, Ana (2009). El Palacio de Justicia: Una Trajedia Colombiana. Bogotá, Colombia: Ícono.
Es uno de los primeros y más importantes libros sobre el tema. Publicado originalmente en inglés en 1993, no fue traducido al español ni publicado en Colombia hasta el 2009 por la editorial Ícono. Tiene un relato detallado de los hechos tal y como se conocían en 1993, y la edición de Ícono tiene una introducción y un epílogo actualizados al 2009.

Es, sin duda, el mejor punto de partida para los que estén interesados en conocer un poco más sobre este trágico evento.
 
* Castro Caycedo, Germán (2008). El palacio sin máscara. Planeta.
Es un libro de testimonios y citas que relata en primera persona los hechos ocurridos durante la toma y retoma del palacio. En adición, muchas mucho de cómo se desarrollaron (o no) las investigaciones periodísticas y judiciales al rededor del Holocausto del Palacio.

Si bien el no aporta MUCHOS elementos nuevos (aunque sí los tiene) más allá de los ya encontrados en el libro de Carrigan, sí lo muestra de forma mucho más cruda y personal ya que contiene testimonios y declaraciones de personas involucradas directamente.

* Gómez Gallego, J. A., Herrera Vergara, J. R., & Pinilla Pinilla, N. (2010). Informe final de la comisión de la verdad sobre los hechos del palacio de justicia. : Editiroial Universidad del Rosario.
Al ser el informe final de la Comisión de la Verdad que, de manera independiente al Gobierno, investigó estos hechos, es el documento más completo y estricto en la forma en la que narra los hechos del Palacio. Contiene información de contexto histórico importante para entender los antecedentes de la toma del palacio y para explicar la exagerada reacción de las fuerzas armadas colombianas. En adición, contradice y esclarece algunos datos aportados en el libro de Carrigan, y lo hace con mayor sustento probatorio. 

* Behar, Olga (2021). Noches de humo: Los protagonistas de la toma del Palacio de Justicia. Ícono.
Es el más distinto de los libros de esta lista. Contrario a los demás, no se centra tanto en los hechos de la toma sino que muestra el recuento de algunos de sus protagonistas. En particular, el testimonio de Clara Helena Enciso --única sobreviviente del M19-- es novedoso. A partir de ese testimonio nos enteramos de cómo se planeó la toma desde el interior del M19, y cómo la vivieron los guerrilleros. 

Es un libro fundamental en este tema.

* Urán Bidegain, Helena (2023). Mi vida y el Palacio: 6 y 7 de noviembre de 1985. Maxi TusQuets.
Es el libro más actualizo de la lista. Si bien el hecho de estar escrito par la hija del magistrado auxiliar Carlos Horacio Uran--que salió con vida del Palacio de la mano de dos soldados, pero que inexplicablemente reapareció dentro del palacio muerto por un tiro de gracia a quema ropas--puede restarle neutralidad al relato, es importante recalcar que eso no es lo que pretende el libro. Es un libro crudo y desnudo en donde una víctima cuenta su historia.

En particular, este libro aporta elementos nuevos sobre los resultados de las investigaciones judiciales al respecto. Es una lectura fundamental sobre este tema.

* Cierre
Del Holocausto del Palacio se han escrito ríos de tinta y, a la fecha, es una historia todavía inconclusa porque no se han cerrado las investigaciones judiciales al respecto. También está pendiente el rendimiento de responsabilidades políticas a toda la cúpula del Ejecutivo que participaron, por acción o por omisión, de la barbarie de la retoma. Sin duda hay mucho más por escribir sobre este tema.

Sin embargo, acá presento 5 libros con diferentes enfoques que, en conjunto, dan un panorama redondo sobre aquel 6 de noviembre en donde brotó toda la pasión, ingenuidad, estupidez, y sevicia que nos caracteriza. 

