#+title: Cómo separar lo importante de lo demás
#+author: Juan E. Gómez-Morantes
#+date: 2024:12:27

Sin importar el sistema de productividad personal que manejes (GTD, PARA, listas de tareas, Matriz de Eisenhower, etc.), todos tienen en el centro una decisión fundamental que se delega a la persona aplicando el método: qué es importante y qué no lo es. En el modelo [[file:3-3-3.org][3:3:3]], por ejemplo, se inicia el día con un bloque de trabajo de 3 horas en "el proyecto más importante que tengas actualmente". Lo complicado de esa frase es determinar qué es lo importante.

Una primera complicación es la confusión entre lo urgente y lo importante. Lo urgente son tareas que tienen una fecha límite de terminación pronta y deben completarse en ese horizonte de tiempo. Ejemplos de esto son responder a un derecho de petición legal o atender una falla técnica que detuvo la operación de un sistema en producción. Esto, sin embargo, no lo hace importante. El derecho de petición puede ser algo rutinario sobre aspectos de muy bajo impacto, y el sistema en producción podrá ser importante para la empresa, pero no para la persona resolviendo el problema. 

Para resolver esto, podemos partir de nuestras metas y objetivos. Como no todas nuestras metas tiene la misma importancia ("tener una buena salud" es más importante que "ver todas las películas de Marvel en su orden cronológico"), debería ser fácil clasificarlas en 3 o 4 niveles de importancia. Si nos guiamos por metas y objetivos, los proyectos o tareas importantes son aquellas que están completamente alineadas (i.e., aportan en gran medida) a nuestras metas y objetivos principales (e.g., ser un académico de talla mundial, tener una relación sana y edificante con mi hija, tener un matrimonio pleno y feliz). Por su parte, las no importantes son aquellas que hacen aportes marginales a dichos objetivos principales, hacen aportes (así sea significativos) a objetivos secundarios, o que --a pesar de ser de obligatorio cumplimiento-- no aportan a ninguno de mis objetivos. 

Otra forma de plantearlo consiste en la alineación con identidades fundamentales. Todos somos muchas cosas --padres, profesionales, deportistas, parejas, hijos, etc.--, pero no todas esas identidades tienen el mismo nivel de importancia. Por ejemplo, yo me defino como "ciclista aficionado", pero ese componente de mi identidad personal no es más importante que los componentes de "padre", "esposo", o "académico". De la misma forma, en mi campo profesional, soy "profesor", "investigador", y "director de programa". Entre estas, es fácil para mi generar una escala de valores para determinar cuál de estas identidades es más importante para mí (/spoiler/: es "investigador"). Siguiendo esa idea, podemos definir lo importante (áreas de responsabilidad, proyectos, hábitos, o tareas) como lo relacionado con los componente identitarios más importantes para nosotros. 

Estas dos perspectivas, afortunadamente, no son excluyentes. Esto pasa porque, incluso en nuestros componentes identitarios fundamentales, hay aspectos que poco aportan a nuestras metas fundamentales. Siendo así, podemos tener un primer criterio de importancia basado en identidad y un segundo criterio basado en impacto dentro esa identidad. 

El problema, ahora, es determinar cuáles son nuestros componentes identitarios fundamentales (i.e., nuestros "soy \________") y los proyectos que nos permiten desarrollar esa identidad al nivel que deseamos. Pero ahí, lastimosamente, no hay métodos ni herramientas más allá de la reflexión personal y la escritura...
