#+title: Cómo publicar páginas web con fórmulas matemáticas en Emacs
#+author: Juan E. Gómez-Morantes
#+date: 2022:07:11

#+html_mathjax: autonumber: all

* Introducción
En notas anteriores ya cubrimos [[file:publicarConEmacs.org][cómo publicar sitios web estáticos con Emacs]]. Sin embargo, estos sitios eran bastante básicos y consistían únicamente de texto. En esta nota vamos a ver cómo publicar fórmulas y contenido matemático usando el mismo sistema de publicación desarrollado en la nota anterior.

* Dos métodos para mostrar contenido matemático
El [[https://orgmode.org/manual/Math-formatting-in-HTML-export.html][manual de =orgmode=]] nos habla de dos formas de mostrar contenido matemático: procesar fórmulas en formato TeX y convertirlas a imágenes, o usar [[https://www.mathjax.org/][MathJax]]. Si bien el método de las imágenes es efectivo, tiene problemas con la ubicación de las imágenes y no tiene tantas funcionalidades como MathJax. Siendo así, esta nota se centrará en el uso de MathJax.

* Formulas en línea
El primer tipo de fórmulas que vamos a ver son fórmulas en línea. Estas son fórmulas que fluyen con el texto como \(x²+y²=0\). Éstas se logran poniendo la fórmula (en sintaxis LaTex) entre los delimitadores =\( \)= dentro de un párrafo. Podría también usarse los delimitadores =$ $=, pero el manual de MathJax no lo recomienda ya que el símbolo =$= puede usarse para otros fines dentro de un texto y esto puede generar errores a la hora de mostrar el contenido.

* Formulas independientes
Para formulas que queramos tener independientes o numeradas, se deben usar los delimitadores =$$ $$=. Por ejemplo, la siguiente línea

#+begin_example
$$x+1\over\sqrt{1-x^2}\label{ref1}$$
#+end_example

Nos genera la siguiente ecuación:

$$x+1\over\sqrt{1-x^2}\label{ref1}$$

** Numeración
Es importante anotar que Emacs no numera las ecuaciones por defecto. Para obtener esta numeración tenemos que activarla agregando la siguiente línea al inicio del archivo =.org= a exportar:

#+begin_example
#+html_mathjax: autonumber: all
#+end_example

También podemos personalizar la variable =org-html-mathjax-options= si queremos que esto aplique para todos los archivos que exportemos. Finalmente, también podemos agregarla a nuestro archivo =.dir-locals.el= si queremos que aplique para todos los archivos de nuestro proyecto, pero sin que se tenga en cuenta para archivos por fuera de éste.

Si por algún motivo queremos queremos hacer referencia a la primera ecuación \ref{ref1}, lo podemos hacer usando:

#+begin_example
\ref{ref1}
#+end_example

Ahora, si por algún motivo queremos incluir una fórmula sin numeración, tenemos que agregar =\nonumber al final de la fórmula: 

#+begin_example
$$x+1\over\sqrt{1-x^2}\nonumber$$
#+end_example

$$x+1\over\sqrt{1-x^2}\nonumber$$

** Ambientes LaTex
Una de las mejores funcionalidades de MathJax es que permite la inclusión de ambientes de ecuaciones de LaTex. Por ejemplo, el siguiente código en un archivo =.org=

#+begin_example
\begin{align} 
x& = y_1-y_2+y_3-y_5+y_8-\dots && \text{por \eqref{ref1}}\\ 
& = y'\circ y^* && \text{por definición}\\ 
& = y(0) y' && \text {por Axioma 1.} 
\end{align} 
#+end_example

Produce:

\begin{align} 
x& = y_1-y_2+y_3-y_5+y_8-\dots && \text{por \eqref{ref1}}\\ 
& = y'\circ y^* && \text{por definición}\\ 
& = y(0) y' && \text {por Axioma 1.} 
\end{align} 

* Cierre
Como ven, las posibilidades de exportar contenido matemático con MathJax son muchas gracias al soporte que tiene de ambientes matemáticos LaTex. El [[http://docs.mathjax.org/en/latest/index.html][manual de MathJax]] ofrece mucha más información como extensiones y opciones de interacción.
